# Generated by Django 5.0.1 on 2024-01-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_alter_tasklist_options_tasklist_manage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={},
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='manage',
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
